/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:34:02 GMT 2021
 */

package org.apache.xmlrpc.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xmlrpc.util.SAXParsers;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.XMLReader;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SAXParsers_ESTest extends SAXParsers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SAXParsers sAXParsers0 = new SAXParsers();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XMLReader xMLReader0 = SAXParsers.newXMLReader();
      assertNotNull(xMLReader0);
  }
}
