/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:27:50 GMT 2021
 */

package org.apache.xmlrpc.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import org.apache.xmlrpc.util.ThreadPool;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ThreadPool_ESTest extends ThreadPool_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool(3920, "vi5*j$xM`&Vp;e<%tN");
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task0);
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task1);
      ThreadPool.Task threadPool_Task2 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task2);
      ThreadPool.Task threadPool_Task3 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task3);
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task4 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task4);
      ThreadPool.Task threadPool_Task5 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task5);
      ThreadPool.Task threadPool_Task6 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task6);
      ThreadPool.Task threadPool_Task7 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task7);
      threadPool0.startTask((ThreadPool.Task) null);
      threadPool0.addTask((ThreadPool.Task) null);
      threadPool0.startTask((ThreadPool.Task) null);
      ThreadPool.Task threadPool_Task8 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task8);
      threadPool0.shutdown();
      threadPool0.addTask((ThreadPool.Task) null);
      threadPool0.shutdown();
      threadPool0.getMaxThreads();
      threadPool0.startTask((ThreadPool.Task) null);
      threadPool0.addTask((ThreadPool.Task) null);
      threadPool0.getMaxThreads();
      threadPool0.addTask((ThreadPool.Task) null);
      threadPool0.getMaxThreads();
      threadPool0.shutdown();
      threadPool0.getMaxThreads();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool((-547), "");
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task0);
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task1);
      threadPool0.shutdown();
      threadPool0.getMaxThreads();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool((-2195), "org.apache.xmlrpc.util.ThreadPool$Poolable");
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool(0, "bQDk)!g7K");
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task0);
      threadPool0.getNumThreads();
      threadPool0.getNumThreads();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool((-1), "");
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task0);
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task1);
      ThreadPool.Task threadPool_Task2 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task2);
      ThreadPool.Task threadPool_Task3 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task3);
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task4 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task5 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.shutdown();
      threadPool0.addTask(threadPool_Task5);
      ThreadPool.Task threadPool_Task6 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task6);
      ThreadPool.Task threadPool_Task7 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.shutdown();
      threadPool0.addTask(threadPool_Task7);
      threadPool0.addTask(threadPool_Task4);
      ThreadPool.Task threadPool_Task8 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task8);
      threadPool0.getMaxThreads();
      ThreadPool.Task threadPool_Task9 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      ThreadPool.Task threadPool_Task10 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task10);
      threadPool0.addTask(threadPool_Task9);
      ThreadPool.Task threadPool_Task11 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      ThreadPool.Task threadPool_Task12 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task12);
      threadPool0.startTask(threadPool_Task11);
      threadPool0.getNumThreads();
      threadPool0.shutdown();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool(0, "}BS_('@$qlYZ_-vga");
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task0);
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task1);
      ThreadPool.Task threadPool_Task2 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task2);
      threadPool0.getMaxThreads();
      ThreadPool.Task threadPool_Task3 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task3);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool((-1), "");
      threadPool0.shutdown();
      threadPool0.getNumThreads();
      threadPool0.shutdown();
      threadPool0.shutdown();
      threadPool0.shutdown();
      threadPool0.shutdown();
      threadPool0.shutdown();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool((-2678), "XLlSwE7P=");
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.shutdown();
      threadPool0.startTask(threadPool_Task0);
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task1);
      threadPool0.addTask((ThreadPool.Task) null);
      threadPool0.getNumThreads();
      threadPool0.getNumThreads();
      threadPool0.shutdown();
      threadPool0.getNumThreads();
      threadPool0.getMaxThreads();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool(0, "3366rVN1%Kvx92$");
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task1);
      ThreadPool.Task threadPool_Task2 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task2);
      ThreadPool.Task threadPool_Task3 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task3);
      threadPool0.addTask(threadPool_Task0);
      ThreadPool.Task threadPool_Task4 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task4);
      threadPool0.getNumThreads();
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task5 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task5);
      threadPool0.getNumThreads();
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task6 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task6);
      threadPool0.startTask((ThreadPool.Task) null);
      threadPool0.shutdown();
      threadPool0.startTask((ThreadPool.Task) null);
      threadPool0.shutdown();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool(0, "+Z1GiCMJk'/Q9.*P");
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.shutdown();
      threadPool0.addTask(threadPool_Task0);
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task1);
      ThreadPool.Task threadPool_Task2 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task2);
      ThreadPool.Task threadPool_Task3 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task3);
      threadPool0.shutdown();
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task4 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(threadPool_Task4).toString();
      threadPool0.addTask(threadPool_Task4);
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task5 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task5);
      ThreadPool.Task threadPool_Task6 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task6);
      threadPool0.startTask((ThreadPool.Task) null);
      threadPool0.getNumThreads();
      threadPool0.getMaxThreads();
      threadPool0.getNumThreads();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ThreadPool threadPool0 = new ThreadPool(1, (String) null);
      ThreadPool.Task threadPool_Task0 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(threadPool_Task0).toString();
      threadPool0.addTask(threadPool_Task0);
      ThreadPool.Task threadPool_Task1 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task1);
      ThreadPool.Task threadPool_Task2 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task2);
      ThreadPool.Task threadPool_Task3 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task4 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(threadPool_Task4).toString();
      threadPool0.startTask(threadPool_Task4);
      threadPool0.addTask(threadPool_Task3);
      threadPool0.shutdown();
      threadPool0.shutdown();
      threadPool0.shutdown();
      threadPool0.shutdown();
      ThreadPool.Task threadPool_Task5 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.startTask(threadPool_Task5);
      ThreadPool.Task threadPool_Task6 = mock(ThreadPool.Task.class, new ViolatedAssumptionAnswer());
      threadPool0.addTask(threadPool_Task6);
  }
}
