/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 11 09:10:40 GMT 2021
 */

package org.apache.xmlrpc.server;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.SequenceInputStream;
import java.net.InetAddress;
import java.util.Enumeration;
import javax.servlet.ServletException;
import javax.servlet.ServletInputStream;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletRequestWrapper;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpServletResponseWrapper;
import org.apache.commons.httpclient.HttpRecoverableException;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;
import org.apache.xmlrpc.common.ServerStreamConnection;
import org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl;
import org.apache.xmlrpc.common.XmlRpcStreamRequestConfig;
import org.apache.xmlrpc.serializer.DefaultXMLWriterFactory;
import org.apache.xmlrpc.serializer.XmlRpcWriter;
import org.apache.xmlrpc.serializer.XmlWriterFactory;
import org.apache.xmlrpc.server.XmlRpcErrorLogger;
import org.apache.xmlrpc.server.XmlRpcLocalStreamServer;
import org.apache.xmlrpc.server.XmlRpcStreamServer;
import org.apache.xmlrpc.webserver.Connection;
import org.apache.xmlrpc.webserver.RequestData;
import org.apache.xmlrpc.webserver.WebServer;
import org.apache.xmlrpc.webserver.XmlRpcServletServer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcStreamServer_ESTest extends XmlRpcStreamServer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      HttpRecoverableException httpRecoverableException0 = new HttpRecoverableException("Y]{oF4m8(rujet.Y:");
      xmlRpcLocalStreamServer0.logError(httpRecoverableException0);
      assertNull(httpRecoverableException0.getReason());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WebServer webServer0 = new WebServer((-44));
      XmlRpcStreamServer xmlRpcStreamServer0 = webServer0.getXmlRpcServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      MockFile mockFile0 = new MockFile("execute: ->", "");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      XmlRpcWriter xmlRpcWriter0 = xmlRpcStreamServer0.getXmlRpcWriter(xmlRpcClientConfigImpl0, mockFileOutputStream0);
      assertNotNull(xmlRpcWriter0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      RequestData requestData0 = new RequestData((Connection) null);
      File file0 = MockFile.createTempFile("nnm", "nnm");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, false);
      OutputStream outputStream0 = xmlRpcLocalStreamServer0.getOutputStream((ServerStreamConnection) null, requestData0, mockFileOutputStream0);
      assertSame(outputStream0, mockFileOutputStream0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      XmlRpcServletServer xmlRpcServletServer0 = new XmlRpcServletServer();
      xmlRpcServletServer0.setErrorLogger((XmlRpcErrorLogger) null);
      XmlRpcErrorLogger xmlRpcErrorLogger0 = xmlRpcServletServer0.getErrorLogger();
      assertNull(xmlRpcErrorLogger0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      Throwable throwable0 = xmlRpcLocalStreamServer0.convertThrowable((Throwable) null);
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WebServer webServer0 = new WebServer(1);
      XmlRpcStreamServer xmlRpcStreamServer0 = webServer0.getXmlRpcServer();
      HttpRecoverableException httpRecoverableException0 = new HttpRecoverableException();
      HttpRecoverableException httpRecoverableException1 = (HttpRecoverableException)xmlRpcStreamServer0.convertThrowable(httpRecoverableException0);
      assertEquals(200, httpRecoverableException1.getReasonCode());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WebServer webServer0 = new WebServer(1);
      XmlRpcStreamServer xmlRpcStreamServer0 = webServer0.getXmlRpcServer();
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("#&Ic*~%BCl?6g");
      // Undeclared exception!
      try { 
        xmlRpcStreamServer0.writeResponse(xmlRpcHttpRequestConfigImpl0, mockFileOutputStream0, xmlRpcHttpRequestConfigImpl0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl cannot be cast to org.apache.xmlrpc.webserver.RequestData
         //
         verifyException("org.apache.xmlrpc.webserver.ConnectionServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("d+OMyt");
      mockFileOutputStream0.close();
      HttpRecoverableException httpRecoverableException0 = new HttpRecoverableException();
      try { 
        xmlRpcLocalStreamServer0.writeError(xmlRpcClientConfigImpl0, mockFileOutputStream0, httpRecoverableException0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to write XML-RPC response: Failed to flush target writer: null
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.writeError(xmlRpcClientConfigImpl0, byteArrayOutputStream0, (Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      InetAddress inetAddress0 = MockInetAddress.anyLocalAddress();
      WebServer webServer0 = new WebServer(1944, inetAddress0);
      XmlRpcStreamServer xmlRpcStreamServer0 = webServer0.getXmlRpcServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      MockFile mockFile0 = new MockFile((String) null, ")YLG;^A[nDa`[]k2;@");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockPrintStream0);
      HttpRecoverableException httpRecoverableException0 = new HttpRecoverableException();
      Throwable throwable0 = httpRecoverableException0.initCause((Throwable) null);
      // Undeclared exception!
      try { 
        xmlRpcStreamServer0.writeError(xmlRpcClientConfigImpl0, objectOutputStream0, throwable0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.xmlrpc.client.XmlRpcClientConfigImpl cannot be cast to org.apache.xmlrpc.webserver.RequestData
         //
         verifyException("org.apache.xmlrpc.webserver.ConnectionServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.logError((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.getXmlRpcWriter(xmlRpcHttpRequestConfigImpl0, (OutputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Writer", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (byte) (-23), 15);
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.getRequest(xmlRpcClientConfigImpl0, byteArrayInputStream0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -23
         //
         verifyException("java.io.ByteArrayInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      WebServer webServer0 = new WebServer(0);
      XmlRpcStreamServer xmlRpcStreamServer0 = webServer0.getXmlRpcServer();
      // Undeclared exception!
      try { 
        xmlRpcStreamServer0.getOutputStream((XmlRpcStreamRequestConfig) null, (ServerStreamConnection) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.getInputStream((XmlRpcStreamRequestConfig) null, (ServerStreamConnection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      XmlRpcServletServer xmlRpcServletServer0 = new XmlRpcServletServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      // Undeclared exception!
      try { 
        xmlRpcServletServer0.execute((XmlRpcStreamRequestConfig) xmlRpcClientConfigImpl0, (ServerStreamConnection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.webserver.XmlRpcServletServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlWriterFactory xmlWriterFactory0 = xmlRpcLocalStreamServer0.getXMLWriterFactory();
      assertNotNull(xmlWriterFactory0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.execute((XmlRpcStreamRequestConfig) null, (ServerStreamConnection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      XmlRpcServletServer xmlRpcServletServer0 = new XmlRpcServletServer();
      xmlRpcServletServer0.setErrorLogger((XmlRpcErrorLogger) null);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(httpServletRequest0).getCharacterEncoding();
      doReturn((ServletInputStream) null).when(httpServletRequest0).getInputStream();
      doReturn((String) null, (String) null).when(httpServletRequest0).getHeader(anyString());
      doReturn((Enumeration) null).when(httpServletRequest0).getHeaders(anyString());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      // Undeclared exception!
      try { 
        xmlRpcServletServer0.execute((HttpServletRequest) httpServletRequestWrapper0, (HttpServletResponse) httpServletResponseWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      XmlRpcServletServer xmlRpcServletServer0 = new XmlRpcServletServer();
      ServletInputStream servletInputStream0 = mock(ServletInputStream.class, new ViolatedAssumptionAnswer());
      doReturn(1, 255, 1, 1).when(servletInputStream0).read();
      doReturn("l=k&KMXe/Q7)fiJ[").when(servletInputStream0).toString();
      Enumeration<String> enumeration0 = (Enumeration<String>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn("l=k&KMXe/Q7)fiJ[").when(httpServletRequest0).getCharacterEncoding();
      doReturn(servletInputStream0).when(httpServletRequest0).getInputStream();
      doReturn("l=k&KMXe/Q7)fiJ[", "l=k&KMXe/Q7)fiJ[").when(httpServletRequest0).getHeader(anyString());
      doReturn(enumeration0).when(httpServletRequest0).getHeaders(anyString());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      try { 
        xmlRpcServletServer0.execute((HttpServletRequest) httpServletRequestWrapper0, (HttpServletResponse) httpServletResponseWrapper0);
        fail("Expecting exception: ServletException");
      
      } catch(ServletException e) {
         //
         // Unsupported encoding: l=k&KMXe/Q7)fiJ[
         //
         verifyException("org.apache.xmlrpc.webserver.XmlRpcServletServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      WebServer webServer0 = new WebServer(3642);
      XmlRpcStreamServer xmlRpcStreamServer0 = webServer0.getXmlRpcServer();
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      Enumeration<BufferedInputStream> enumeration0 = (Enumeration<BufferedInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false, false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      try { 
        xmlRpcStreamServer0.getRequest(xmlRpcHttpRequestConfigImpl0, sequenceInputStream0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to parse XML-RPC request: Premature end of file.
         //
         verifyException("org.apache.xmlrpc.server.XmlRpcStreamServer", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      boolean boolean0 = xmlRpcLocalStreamServer0.isContentLengthRequired(xmlRpcHttpRequestConfigImpl0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      // Undeclared exception!
      try { 
        xmlRpcLocalStreamServer0.writeResponse(xmlRpcClientConfigImpl0, (OutputStream) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Writer", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      XmlRpcServletServer xmlRpcServletServer0 = new XmlRpcServletServer();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(httpServletRequest0).getCharacterEncoding();
      doReturn((ServletInputStream) null).when(httpServletRequest0).getInputStream();
      doReturn((String) null, (String) null).when(httpServletRequest0).getHeader(anyString());
      doReturn((Enumeration) null).when(httpServletRequest0).getHeaders(anyString());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null, (ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      // Undeclared exception!
      try { 
        xmlRpcServletServer0.execute((HttpServletRequest) httpServletRequestWrapper0, (HttpServletResponse) httpServletResponseWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ByteArrayOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      XmlRpcServletServer xmlRpcServletServer0 = new XmlRpcServletServer();
      XmlRpcErrorLogger xmlRpcErrorLogger0 = xmlRpcServletServer0.getErrorLogger();
      xmlRpcServletServer0.setErrorLogger(xmlRpcErrorLogger0);
      assertEquals(0, xmlRpcServletServer0.getMaxThreads());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("d+OMyt");
      HttpRecoverableException httpRecoverableException0 = new HttpRecoverableException();
      xmlRpcLocalStreamServer0.writeError(xmlRpcClientConfigImpl0, mockFileOutputStream0, httpRecoverableException0);
      assertFalse(xmlRpcClientConfigImpl0.isEnabledForExtensions());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      XmlRpcLocalStreamServer xmlRpcLocalStreamServer0 = new XmlRpcLocalStreamServer();
      DefaultXMLWriterFactory defaultXMLWriterFactory0 = new DefaultXMLWriterFactory();
      xmlRpcLocalStreamServer0.setXMLWriterFactory(defaultXMLWriterFactory0);
      assertEquals(0, xmlRpcLocalStreamServer0.getMaxThreads());
  }
}
