/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:47:01 GMT 2021
 */

package org.apache.xmlrpc.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.apache.xmlrpc.XmlRpcConfig;
import org.apache.xmlrpc.XmlRpcRequest;
import org.apache.xmlrpc.XmlRpcRequestConfig;
import org.apache.xmlrpc.client.AsyncCallback;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfig;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;
import org.apache.xmlrpc.client.XmlRpcTransportFactory;
import org.apache.xmlrpc.common.XmlRpcWorkerFactory;
import org.apache.xmlrpc.serializer.XmlWriterFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcClient_ESTest extends XmlRpcClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      Object[] objectArray0 = new Object[0];
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = (XmlRpcClientConfigImpl)xmlRpcClient0.getClientConfig();
      xmlRpcClient0.executeAsync((XmlRpcClientConfig) xmlRpcClientConfigImpl0, ":\u0004.$[b", objectArray0, (AsyncCallback) null);
      assertFalse(xmlRpcClientConfigImpl0.isEnabledForExceptions());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = (XmlRpcClientConfigImpl)xmlRpcClient0.getClientConfig();
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      xmlRpcClient0.executeAsync((XmlRpcClientConfig) xmlRpcClientConfigImpl0, "", (List) null, asyncCallback0);
      assertNull(xmlRpcClientConfigImpl0.getBasicUserName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.executeAsync("", (List) null, (AsyncCallback) null);
      assertEquals(0, xmlRpcClient0.getMaxThreads());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setXmlWriterFactory((XmlWriterFactory) null);
      XmlWriterFactory xmlWriterFactory0 = xmlRpcClient0.getXmlWriterFactory();
      assertNull(xmlWriterFactory0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setTransportFactory((XmlRpcTransportFactory) null);
      XmlRpcTransportFactory xmlRpcTransportFactory0 = xmlRpcClient0.getTransportFactory();
      assertNull(xmlRpcTransportFactory0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcWorkerFactory xmlRpcWorkerFactory0 = xmlRpcClient0.getDefaultXmlRpcWorkerFactory();
      assertEquals(0, xmlRpcWorkerFactory0.getCurrentRequests());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setConfig((XmlRpcClientConfig) null);
      XmlRpcConfig xmlRpcConfig0 = xmlRpcClient0.getConfig();
      assertNull(xmlRpcConfig0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setWorkerFactory((XmlRpcWorkerFactory) null);
      XmlRpcRequest xmlRpcRequest0 = mock(XmlRpcRequest.class, new ViolatedAssumptionAnswer());
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        xmlRpcClient0.executeAsync(xmlRpcRequest0, asyncCallback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      Object[] objectArray0 = new Object[2];
      xmlRpcClient0.setConfig((XmlRpcClientConfig) null);
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        xmlRpcClient0.executeAsync(":FWj>p", objectArray0, asyncCallback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The request configuration must not be null.
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClientRequestImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcClientConfig xmlRpcClientConfig0 = xmlRpcClient0.getClientConfig();
      xmlRpcClient0.setWorkerFactory((XmlRpcWorkerFactory) null);
      Object[] objectArray0 = new Object[5];
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute(xmlRpcClientConfig0, "", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setWorkerFactory((XmlRpcWorkerFactory) null);
      XmlRpcRequest xmlRpcRequest0 = mock(XmlRpcRequest.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute(xmlRpcRequest0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcRequestConfig xmlRpcRequestConfig0 = mock(XmlRpcRequestConfig.class, new ViolatedAssumptionAnswer());
      XmlRpcRequest xmlRpcRequest0 = mock(XmlRpcRequest.class, new ViolatedAssumptionAnswer());
      doReturn(xmlRpcRequestConfig0).when(xmlRpcRequest0).getConfig();
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute(xmlRpcRequest0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.xmlrpc.XmlRpcRequestConfig$MockitoMock$1216554064 cannot be cast to org.apache.xmlrpc.client.XmlRpcHttpClientConfig
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcSunHttpTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setWorkerFactory((XmlRpcWorkerFactory) null);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute("org.apache.xmlrpc.client.XmlRpcClient", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setWorkerFactory((XmlRpcWorkerFactory) null);
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute("", (List) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        xmlRpcClient0.executeAsync((XmlRpcClientConfig) null, "gd!u>4S#Kk:z)I", (List) null, asyncCallback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The request configuration must not be null.
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClientRequestImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcRequest xmlRpcRequest0 = mock(XmlRpcRequest.class, new ViolatedAssumptionAnswer());
      doReturn((XmlRpcRequestConfig) null).when(xmlRpcRequest0).getConfig();
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute(xmlRpcRequest0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcSunHttpTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.executeAsync((XmlRpcRequest) null, (AsyncCallback) null);
      assertEquals(0, xmlRpcClient0.getMaxThreads());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcClientConfig xmlRpcClientConfig0 = xmlRpcClient0.getClientConfig();
      Object[] objectArray0 = new Object[5];
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute(xmlRpcClientConfig0, "", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute("org.apache.xmlrpc.client.XmlRpcClient", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = (XmlRpcClientConfigImpl)xmlRpcClient0.getConfig();
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        xmlRpcClient0.executeAsync((XmlRpcClientConfig) xmlRpcClientConfigImpl0, (String) null, (Object[]) null, asyncCallback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The method name must not be null.
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClientRequestImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute("", (List) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcTransportFactory xmlRpcTransportFactory0 = xmlRpcClient0.getTransportFactory();
      xmlRpcClient0.setTransportFactory(xmlRpcTransportFactory0);
      assertEquals(0, xmlRpcClient0.getMaxThreads());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        xmlRpcClient0.executeAsync((String) null, (List) null, asyncCallback0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The method name must not be null.
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcClientRequestImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcClientConfig xmlRpcClientConfig0 = xmlRpcClient0.getClientConfig();
      // Undeclared exception!
      try { 
        xmlRpcClient0.execute(xmlRpcClientConfig0, "= _qgc+6N!x)U3&t", (List) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockURL", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      AsyncCallback asyncCallback0 = mock(AsyncCallback.class, new ViolatedAssumptionAnswer());
      xmlRpcClient0.executeAsync("V&(ut;5", (Object[]) null, asyncCallback0);
      assertEquals(0, xmlRpcClient0.getMaxThreads());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlWriterFactory xmlWriterFactory0 = xmlRpcClient0.getXmlWriterFactory();
      xmlRpcClient0.setXmlWriterFactory(xmlWriterFactory0);
      assertEquals(0, xmlRpcClient0.getMaxThreads());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      xmlRpcClient0.setConfig((XmlRpcClientConfig) null);
      XmlRpcClientConfig xmlRpcClientConfig0 = xmlRpcClient0.getClientConfig();
      assertNull(xmlRpcClientConfig0);
  }
}
