/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:41:56 GMT 2021
 */

package org.apache.xmlrpc.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Date;
import java.util.LinkedList;
import org.apache.xmlrpc.XmlRpcRequest;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;
import org.apache.xmlrpc.client.XmlRpcClientRequestImpl;
import org.apache.xmlrpc.client.XmlRpcLocalTransport;
import org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcLocalTransport_ESTest extends XmlRpcLocalTransport_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      // Undeclared exception!
      try { 
        xmlRpcLocalTransport0.sendRequest((XmlRpcRequest) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      Object[] objectArray0 = new Object[6];
      xmlRpcClientConfigImpl0.setEnabledForExtensions(true);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "id is null", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method id is null: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) ";";
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, ";", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method ;: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      LinkedList<Date> linkedList0 = new LinkedList<Date>();
      MockDate mockDate0 = new MockDate();
      linkedList0.add((Date) mockDate0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcHttpRequestConfigImpl0, "", linkedList0);
      // Undeclared exception!
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl cannot be cast to org.apache.xmlrpc.client.XmlRpcLocalClientConfig
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(4116);
      linkedList0.add((Object) integer0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "V^RMyHrd.A<", linkedList0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method V^RMyHrd.A<: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      LinkedList<XmlRpcClientConfigImpl> linkedList0 = new LinkedList<XmlRpcClientConfigImpl>();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      linkedList0.add(xmlRpcClientConfigImpl0);
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) linkedList0;
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "&1iyo|WQKC?L]-`uq", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 0 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      LinkedList<XmlRpcClientConfigImpl> linkedList0 = new LinkedList<XmlRpcClientConfigImpl>();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) linkedList0;
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "&1iyo|WQKC?L]-`uq", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) linkedList0;
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcHttpRequestConfigImpl0, "http.protocol.reject-head-body", objectArray0);
      Double double0 = new Double(1.0);
      linkedList0.add(double0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }
}
