/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:45:42 GMT 2021
 */

package org.apache.xmlrpc.client;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcLocalTransportFactory;
import org.apache.xmlrpc.client.XmlRpcTransport;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcLocalTransportFactory_ESTest extends XmlRpcLocalTransportFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlRpcLocalTransportFactory xmlRpcLocalTransportFactory0 = new XmlRpcLocalTransportFactory((XmlRpcClient) null);
      XmlRpcTransport xmlRpcTransport0 = xmlRpcLocalTransportFactory0.getTransport();
      assertNotNull(xmlRpcTransport0);
  }
}
