/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 11 08:16:24 GMT 2021
 */

package org.apache.xmlrpc.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Date;
import java.util.LinkedList;
import org.apache.xmlrpc.XmlRpcRequest;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;
import org.apache.xmlrpc.client.XmlRpcClientRequestImpl;
import org.apache.xmlrpc.client.XmlRpcLocalTransport;
import org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcLocalTransport_ESTest extends XmlRpcLocalTransport_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      // Undeclared exception!
      try { 
        xmlRpcLocalTransport0.sendRequest((XmlRpcRequest) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      xmlRpcClientConfigImpl0.setEnabledForExtensions(true);
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "0!K6[t-XP", linkedList0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method 0!K6[t-XP: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) "";
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      LinkedList<Date> linkedList0 = new LinkedList<Date>();
      MockDate mockDate0 = new MockDate();
      linkedList0.push(mockDate0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "7k|]Jd13'iy5Mp8I", linkedList0);
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method 7k|]Jd13'iy5Mp8I: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(29);
      linkedList0.add(integer0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "j", linkedList0);
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport((XmlRpcClient) null);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method j: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      LinkedList<Double> linkedList0 = new LinkedList<Double>();
      Object[] objectArray0 = new Object[8];
      objectArray0[0] = (Object) linkedList0;
      Double double0 = new Double(9.373466111268732);
      linkedList0.add(double0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcHttpRequestConfigImpl0, "", objectArray0);
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      LinkedList<XmlRpcClientConfigImpl> linkedList0 = new LinkedList<XmlRpcClientConfigImpl>();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      linkedList0.add(xmlRpcClientConfigImpl0);
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) linkedList0;
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "h$m(^I&.#$eXLv", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 0 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      LinkedList<XmlRpcClientConfigImpl> linkedList0 = new LinkedList<XmlRpcClientConfigImpl>();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) linkedList0;
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "h$m(^I&.#$eXLv", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      Object[] objectArray0 = new Object[2];
      objectArray0[0] = (Object) "";
      objectArray0[1] = (Object) "";
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcHttpRequestConfigImpl0, "", objectArray0);
      // Undeclared exception!
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl cannot be cast to org.apache.xmlrpc.client.XmlRpcLocalClientConfig
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }
}
