/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:31:24 GMT 2021
 */

package org.apache.xmlrpc.serializer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.xmlrpc.serializer.CalendarSerializer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.helpers.XMLFilterImpl;
import org.xml.sax.helpers.XMLReaderAdapter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalendarSerializer_ESTest extends CalendarSerializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CalendarSerializer calendarSerializer0 = new CalendarSerializer();
      XMLReaderAdapter xMLReaderAdapter0 = new XMLReaderAdapter();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        calendarSerializer0.write(xMLReaderAdapter0, object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.util.Calendar
         //
         verifyException("org.apache.ws.commons.util.XsDateTimeFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CalendarSerializer calendarSerializer0 = new CalendarSerializer();
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      // Undeclared exception!
      try { 
        calendarSerializer0.write(xMLFilterImpl0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The Calendar argument must not be null.
         //
         verifyException("org.apache.ws.commons.util.XsDateTimeFormat", e);
      }
  }
}
