/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:34:49 GMT 2021
 */

package org.apache.xmlrpc.serializer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.xmlrpc.serializer.StringSerializer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.xml.sax.ContentHandler;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringSerializer_ESTest extends StringSerializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringSerializer stringSerializer0 = new StringSerializer();
      ContentHandler contentHandler0 = mock(ContentHandler.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        stringSerializer0.write(contentHandler0, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringSerializer stringSerializer0 = new StringSerializer();
      ContentHandler contentHandler0 = mock(ContentHandler.class, new ViolatedAssumptionAnswer());
      stringSerializer0.write(contentHandler0, "org.apache.xmlrpc.serializer.StringSerializer");
  }
}
