/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 11 10:37:09 GMT 2021
 */

package org.apache.xmlrpc.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Date;
import java.util.LinkedList;
import org.apache.xmlrpc.XmlRpcRequest;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfig;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;
import org.apache.xmlrpc.client.XmlRpcClientRequestImpl;
import org.apache.xmlrpc.client.XmlRpcLocalTransport;
import org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcLocalTransport_ESTest extends XmlRpcLocalTransport_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      // Undeclared exception!
      try { 
        xmlRpcLocalTransport0.sendRequest((XmlRpcRequest) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      Object[] objectArray0 = new Object[0];
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcHttpRequestConfigImpl0, "HAnT\"']*8R gB1$)w`", objectArray0);
      // Undeclared exception!
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.xmlrpc.common.XmlRpcHttpRequestConfigImpl cannot be cast to org.apache.xmlrpc.client.XmlRpcLocalClientConfig
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      Object[] objectArray0 = new Object[5];
      xmlRpcClientConfigImpl0.setEnabledForExtensions(true);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method : null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Double double0 = new Double((-1796.41));
      linkedList0.add((Object) double0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, " has invalid type, if isEnabledForExtensions() == false", linkedList0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method  has invalid type, if isEnabledForExtensions() == false: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) "M%eMRgZ3dO(z:g2)rQ3";
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcHttpRequestConfigImpl xmlRpcHttpRequestConfigImpl0 = new XmlRpcHttpRequestConfigImpl();
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcHttpRequestConfigImpl0, "M%eMRgZ3dO(z:g2)rQ3", objectArray0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      LinkedList<Date> linkedList0 = new LinkedList<Date>();
      MockDate mockDate0 = new MockDate((-1), (-2054), (-1));
      linkedList0.add((Date) mockDate0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "9C*0}fAhuDW^S,6:dr", linkedList0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method 9C*0}fAhuDW^S,6:dr: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      XmlRpcClient xmlRpcClient0 = new XmlRpcClient();
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport(xmlRpcClient0);
      XmlRpcClientConfig xmlRpcClientConfig0 = xmlRpcClient0.getClientConfig();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer((-2551));
      linkedList0.add(integer0);
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfig0, "zO)%@;@", linkedList0);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Failed to invoke method zO)%@;@: null
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LinkedList<XmlRpcClientConfigImpl> linkedList0 = new LinkedList<XmlRpcClientConfigImpl>();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      Object[] objectArray0 = new Object[5];
      linkedList0.add(xmlRpcClientConfigImpl0);
      objectArray0[0] = (Object) linkedList0;
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "", objectArray0);
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport((XmlRpcClient) null);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 0 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      LinkedList<XmlRpcClientConfigImpl> linkedList0 = new LinkedList<XmlRpcClientConfigImpl>();
      XmlRpcClientConfigImpl xmlRpcClientConfigImpl0 = new XmlRpcClientConfigImpl();
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) linkedList0;
      XmlRpcClientRequestImpl xmlRpcClientRequestImpl0 = new XmlRpcClientRequestImpl(xmlRpcClientConfigImpl0, "", objectArray0);
      XmlRpcLocalTransport xmlRpcLocalTransport0 = new XmlRpcLocalTransport((XmlRpcClient) null);
      try { 
        xmlRpcLocalTransport0.sendRequest(xmlRpcClientRequestImpl0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Parameter 1 has invalid type, if isEnabledForExtensions() == false
         //
         verifyException("org.apache.xmlrpc.client.XmlRpcLocalTransport", e);
      }
  }
}
