/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:35:39 GMT 2021
 */

package org.apache.xmlrpc.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.xmlrpc.parser.BigIntegerParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.xml.sax.SAXParseException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BigIntegerParser_ESTest extends BigIntegerParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BigIntegerParser bigIntegerParser0 = new BigIntegerParser();
      try { 
        bigIntegerParser0.setResult("AX1M-/~");
        fail("Expecting exception: SAXParseException");
      
      } catch(SAXParseException e) {
         //
         // Failed to parse BigInteger value: AX1M-/~
         //
         verifyException("org.apache.xmlrpc.parser.BigIntegerParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BigIntegerParser bigIntegerParser0 = new BigIntegerParser();
      // Undeclared exception!
      try { 
        bigIntegerParser0.setResult((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigInteger", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BigIntegerParser bigIntegerParser0 = new BigIntegerParser();
      bigIntegerParser0.setResult("0");
  }
}
