/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 01 06:33:27 GMT 2021
 */

package org.apache.xmlrpc.common;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xmlrpc.common.XmlRpcExtensionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlRpcExtensionException_ESTest extends XmlRpcExtensionException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlRpcExtensionException xmlRpcExtensionException0 = new XmlRpcExtensionException("-xc>[iAC.%R");
      assertEquals(0, xmlRpcExtensionException0.code);
  }
}
